import Image from "next/image";
import styles from "./page.module.css";
import Navbar from "@/components/Navbar";
import Carousel from "@/components/Carousel";

// ✅ New way: metadata for title, description, etc.
export const metadata = {
  title: "My app",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <header>
        <Navbar />
        <Carousel />
      </header>
      <main className={styles.main}></main>
      <footer className={styles.footer}></footer>
    </>
  );
}
